### PR TITLE
Support match IPV4 TTL

### PR DESCRIPTION
**Pull request by heshengyuan1311**
- Support match IPV4 TTL function

This patch depend on another patch in libOpenflow:
 https://github.com/antrea-io/libOpenflow/pull/15

Signed-off-by: Isaac He <heshengyuan1311@163.com>

### CODE REVIEW

**Comment by heshengyuan1311** [comment]
@wenyingd @hangyan @tnqn  Can you help review and merge this PR? Thanks!

**Review by tnqn — COMMENTED** [review]
LGTM, guess we need to merge https://github.com/antrea-io/libOpenflow/pull/15/files first and update go.mod.

**Comment by heshengyuan1311** [comment]
> LGTM, guess we need to merge [antrea-io/libOpenflow#15](https://github.com/antrea-io/libOpenflow/pull/15) first and update go.mod.

Yes you are right.

I add the following instruction into git log
```
This patch depend on another patch in libOpenflow:
    https://github.com/antrea-io/libOpenflow/pull/15
```

**Comment by heshengyuan1311** [comment]
I updated the go.mod to support libopenflow's TtlField.
Can you review this pr again ? Thanks
@tnqn @wenyingd

**Review by wenyingd — APPROVED** [review]
LGTM

**Pull request merged**
