### PR TITLE
Enable write metadata instruction

### PR DESCRIPTION
**Pull request by commandgjj**
The write metadata instruction was missing to be added when
generating flow message. This patch will fix it. After this
fix, the write metadata function will work.

Signed-off-by: Jinjun Gao <gjinjun@gmail.com>

### CODE REVIEW

**Comment by commandgjj** [comment]
@hangyan @tnqn @wenyingd Can you help check this PR?

**Review by wenyingd — COMMENTED** [review]
Code is LGTM, please update the VERSION in the meanwhile.

**Review by wenyingd — APPROVED** [review]
LGTM. 
@antoninbas Could you help check if the VERSION change is as expect?

**Pull request merged**
