### PR TITLE
Support conntrack zone range action

### PR DESCRIPTION
**Pull request by gran-vmv**
Signed-off-by: gran <gran@vmware.com>

### CODE REVIEW

**Comment by gran-vmv** [comment]
Test passed.
```
INFO[0035] flowList: [cookie=0x10103e9, table=0, priority=100,tcp,in_port=1,tp_src=8000,tp_dst=9000,tcp_flags=+syn+ack actions=set_field:4000->tcp_src,goto_table:1 cookie=0x20103e9, table=0, priority=100,udp,in_port=1,tp_src=8000,tp_dst=9000 actions=set_field:4000->udp_src,set_field:5000->udp_dst,goto_table:1 cookie=0xf, table=0, priority=100,ip,dl_src=22:11:11:11:11:11,nw_src=192.168.2.11 actions=goto_table:1 cookie=0x10, table=0, priority=100,ip,dl_src=22:11:11:11:11:12,nw_src=192.168.2.12 actions=goto_table:1 cookie=0x23, table=0, priority=100,ip,dl_src=33:33:11:11:11:11,nw_src=192.168.1.10 actions=note:74.65.73.74.3a.61.62.63.64.20.65.66.67.73.2e.00.00.00.00.00.00.00,goto_table:1 cookie=0x13, table=0, priority=100,ip,in_port=11 actions=group:2 cookie=0x2b, table=0, priority=100,ip,in_port=108 actions=ct(commit,table=1,zone=65281,exec(load:0xf009->NXM_NX_CT_MARK[])),resubmit(,1),resubmit(,2)] 
INFO[0035] flowList: [cookie=0x10103e9, table=0, priority=100,tcp,in_port=1,tp_src=8000,tp_dst=9000,tcp_flags=+syn+ack actions=set_field:4000->tcp_src,goto_table:1 cookie=0x20103e9, table=0, priority=100,udp,in_port=1,tp_src=8000,tp_dst=9000 actions=set_field:4000->udp_src,set_field:5000->udp_dst,goto_table:1 cookie=0xf, table=0, priority=100,ip,dl_src=22:11:11:11:11:11,nw_src=192.168.2.11 actions=goto_table:1 cookie=0x10, table=0, priority=100,ip,dl_src=22:11:11:11:11:12,nw_src=192.168.2.12 actions=goto_table:1 cookie=0x23, table=0, priority=100,ip,dl_src=33:33:11:11:11:11,nw_src=192.168.1.10 actions=note:74.65.73.74.3a.61.62.63.64.20.65.66.67.73.2e.00.00.00.00.00.00.00,goto_table:1 cookie=0x13, table=0, priority=100,ip,in_port=11 actions=group:2] 
INFO[0035] flowList: [cookie=0x10103e9, table=0, priority=100,tcp,in_port=1,tp_src=8000,tp_dst=9000,tcp_flags=+syn+ack actions=set_field:4000->tcp_src,goto_table:1 cookie=0x20103e9, table=0, priority=100,udp,in_port=1,tp_src=8000,tp_dst=9000 actions=set_field:4000->udp_src,set_field:5000->udp_dst,goto_table:1 cookie=0xf, table=0, priority=100,ip,dl_src=22:11:11:11:11:11,nw_src=192.168.2.11 actions=goto_table:1 cookie=0x10, table=0, priority=100,ip,dl_src=22:11:11:11:11:12,nw_src=192.168.2.12 actions=goto_table:1 cookie=0x23, table=0, priority=100,ip,dl_src=33:33:11:11:11:11,nw_src=192.168.1.10 actions=note:74.65.73.74.3a.61.62.63.64.20.65.66.67.73.2e.00.00.00.00.00.00.00,goto_table:1 cookie=0x13, table=0, priority=100,ip,in_port=11 actions=group:2 cookie=0x2c, table=0, priority=100,ip,in_port=108 actions=ct(table=1,zone=NXM_NX_REG1[0..15],nat),goto_table:1] 
INFO[0035] flowList: [cookie=0x10103e9, table=0, priority=100,tcp,in_port=1,tp_src=8000,tp_dst=9000,tcp_flags=+syn+ack actions=set_field:4000->tcp_src,goto_table:1 cookie=0x20103e9, table=0, priority=100,udp,in_port=1,tp_src=8000,tp_dst=9000 actions=set_field:4000->udp_src,set_field:5000->udp_dst,goto_table:1 cookie=0xf, table=0, priority=100,ip,dl_src=22:11:11:11:11:11,nw_src=192.168.2.11 actions=goto_table:1 cookie=0x10, table=0, priority=100,ip,dl_src=22:11:11:11:11:12,nw_src=192.168.2.12 actions=goto_table:1 cookie=0x23, table=0, priority=100,ip,dl_src=33:33:11:11:11:11,nw_src=192.168.1.10 actions=note:74.65.73.74.3a.61.62.63.64.20.65.66.67.73.2e.00.00.00.00.00.00.00,goto_table:1 cookie=0x13, table=0, priority=100,ip,in_port=11 actions=group:2] 
INFO[0035] flowList: [cookie=0x10103e9, table=0, priority=100,tcp,in_port=1,tp_src=8000,tp_dst=9000,tcp_flags=+syn+ack actions=set_field:4000->tcp_src,goto_table:1 cookie=0x20103e9, table=0, priority=100,udp,in_port=1,tp_src=8000,tp_dst=9000 actions=set_field:4000->udp_src,set_field:5000->udp_dst,goto_table:1 cookie=0xf, table=0, priority=100,ip,dl_src=22:11:11:11:11:11,nw_src=192.168.2.11 actions=goto_table:1 cookie=0x10, table=0, priority=100,ip,dl_src=22:11:11:11:11:12,nw_src=192.168.2.12 actions=goto_table:1 cookie=0x23, table=0, priority=100,ip,dl_src=33:33:11:11:11:11,nw_src=192.168.1.10 actions=note:74.65.73.74.3a.61.62.63.64.20.65.66.67.73.2e.00.00.00.00.00.00.00,goto_table:1 cookie=0x13, table=0, priority=100,ip,in_port=11 actions=group:2 cookie=0x2d, table=0, priority=100,ip,in_port=109 actions=dec_ttl] 

```

**Comment by commandgjj** [comment]
> Signed-off-by: gran [gran@vmware.com](mailto:gran@vmware.com)

Seems this change is the same with PR https://github.com/antrea-io/ofnet/pull/18. Why need a new PR to do it?

**Comment by gran-vmv** [comment]
> > Signed-off-by: gran [gran@vmware.com](mailto:gran@vmware.com)
> 
> Seems this change is the same with PR #18. Why need a new PR to do it?

Oh, I checked PR #18 and it is OK.
Could you correct version and add some testcase like this PR?

**Comment by commandgjj** [comment]
> > > Signed-off-by: gran [gran@vmware.com](mailto:gran@vmware.com)
> > 
> > 
> > Seems this change is the same with PR #18. Why need a new PR to do it?
> 
> Oh, I checked PR #18 and it is OK. Could you correct version and add some testcase like this PR?

Done.

**Pull request closed without merging**
