### PR TITLE
Remove unnecessary deletion of ovs groups

### PR DESCRIPTION
**Pull request by pedh**
Those codes are from the original contiv implementation and are unnecessary. Contiv uses ovs groups for handling network floods, and clear all the ovs groups on ofSwitch initialization. This behavior is not helpful in common context, and may cause packet losses of certain traffics.

### CODE REVIEW

**Review by tnqn — COMMENTED** [review]
@antoninbas I remember you added a group cleanup somewhere when initializing. Does this change affect it?

**Review by antoninbas — COMMENTED** [review]
@tnqn thanks for checking with me. We cannot merge this PR as it is without making changes in the Antrea Agent code. At the moment we rely on this ofnet behavior: https://github.com/antrea-io/antrea/blob/9a52de90e90a8beeb512f56c51b670d93ec82325/pkg/agent/agent.go#L369-L374. In particular, calls to `ofClient.ReplayFlows` may fail, and I assume calls to `ofClient.InstallServiceGroup` may fail as well after an Agent restart (with no OVS restart). This is because `OFPGC_ADD` will fail if the group already exists, while for flows, `OFPFC_ADD` will roughly act as a modify operation if the flow already exists (and so we don't have to worry about duplicate adds).

**Comment by antoninbas** [comment]
I believe we should be able to merge this PR if we move this code to https://github.com/antrea-io/antrea/blob/9a52de90e90a8beeb512f56c51b670d93ec82325/pkg/agent/openflow/client.go#L723. The groups need to be deleted every time the OF switch reconnects to Antrea (could be because of an Agent restart, or for any other reason).

**Comment by tnqn** [comment]
@antoninbas thanks for confirming. Maybe we could look at where the normal flows are removed and put group cleanup same place?

**Comment by antoninbas** [comment]
@tnqn we don't really have an equivalent for normal flow because of the different behavior for `OFPFC_ADD` (which won't fail if the flow already exists).

**Comment by tnqn** [comment]
You are right. Now I remember we just replay all flows with new cookie and delete the stale ones regardless of whether they exist.

**Pull request closed without merging**
